<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property string $album MySQL type varchar(255)
 * @property ?int $albumId MySQL type integer
 * @property int $plays MySQL type integer
 * @property int $rank MySQL type integer
 */
abstract class Album extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, \PHPFUI\ORM\FieldDefinition> */
	protected static array $fields = [];

	/** @var array<string> */
	protected static array $primaryKeys = ['albumId', ];

	protected static string $table = 'album';

	public function initFieldDefinitions() : static
		{
		if (! \count(static::$fields))
			{
			static::$fields = [
				'album' => new \PHPFUI\ORM\FieldDefinition('varchar(255)', 'string', 255, false, '', ),
				'albumId' => new \PHPFUI\ORM\FieldDefinition('integer', 'int', 0, true, ),
				'plays' => new \PHPFUI\ORM\FieldDefinition('integer', 'int', 0, false, 0, ),
				'rank' => new \PHPFUI\ORM\FieldDefinition('integer', 'int', 0, false, 0, ),
			];
			}

		return $this;
		}
	}
